package com.example.demo.controller;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Controller;
import org.springframework.web.bind.annotation.GetMapping;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.ResponseBody;

import com.example.demo.model.Country;
import com.example.demo.repository.CountryRepository;

@Controller
@RequestMapping(path = "/") // renvoie les valeurs définies dans la classe ici
public class CountryController {

	@Autowired // This means to get the bean called userRepository
	// Which is auto-generated by Spring, we will use it to handle the data
	private CountryRepository countryRepository;

	@GetMapping(path = "/country")
	public @ResponseBody Iterable<Country> getAllCountries() {
		// This returns a JSON or XML with the users
		return countryRepository.findAll();

	}
}
